### ISSUE TITLE
Minor typos and functions arguments cannot mix characters and numbers.

### ISSUE THREAD

**Issue by yingxingcheng** [reproducible-reporting/reprepbuild#2]
https://github.com/reproducible-reporting/reprepbuild/blob/40f2f7751209f0b441b9a0c5870851ab1e2205e5/src/reprepbuild/utils.py#L95-L102

`re` is not imported and the regular expression cannot be a string mixing characters and numbers.

I'll pull a request to fix this later.

**Comment by tovrstra** [comment]
Fixed by #3
