### ISSUE TITLE
How can I add dependencies for dynamically generated LaTeX tables?

### ISSUE THREAD

**Issue by yingxingcheng** [reproducible-reporting/reprepbuild#6]
If one has a latex file like the following, and these tables are created by a python script. 
Is it possible to add dependencies for these latex tables?

```tex
\begin{document}

\input{table_1.tex}
\input{table_2.tex}
...
\input{table_100.tex}

\end{document}
```

**Comment by tovrstra** [comment]
They should get picked up automatically, but I noticed there were some issues with that due to some internals of `latexmk`. Fix is on the way...

**Comment by tovrstra** [comment]
Can you test if 98ea0f4 fixes your problem?
